@baseUrl = https://localhost:7011/api/news

POST {{baseUrl}}/register-news
Content-Type: application/json

{
    "Title": "About Cloud",
    "Description": "The Cloud Ecosystem",
    "Body": "Cloud computing is the on-demand availability of computer system resources, especially data storage and computing power, without direct active management by the user. Large clouds often have functions distributed over multiple locations, each of which is a data center.",
    "KeywordsCodes":
    [
        "4AA264FA-DBF4-4F51-A9D4-4E76F58BF243"
    ]
}

###

@id = 2
GET {{baseUrl}}/get-news-detail/{{id}}
Content-Type: application/json